org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=ultimateshield
mod_name=Ultimate Shield
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.molishaai.ultimateshield
mod_authors=molishaai97-art
mod_description=Removes vanilla shield cooldown (including axe disable), lets you attack with any main-hand weapon while blocking, keeps full movement and sprint, and stops shield durability loss.
